#####################################################
# ~ ZFAD: generate protein alignment plot for every gene tested ~
#
# using function proteinAligner (in utilities/)
#
# Francois Kroll 2023
# francois@kroll.be
#####################################################



# packages ----------------------------------------------------------------

library(here)


# load function -----------------------------------------------------------

source(here('utilities', 'proteinAligner_NEWTHEME.R'))


# psen1 -------------------------------------------------------------------

# from https://rest.uniprot.org/uniprotkb/P49768.fasta
hPsen1 <- 'MTELPAPLSYFQNAQMSEDNHLSNTVRSQNDNRERQEHNDRRSLGHPEPLSNGRPQGNSR
QVVEQDEEEDEELTLKYGAKHVIMLFVPVTLCMVVVVATIKSVSFYTRKDGQLIYTPFTE
DTETVGQRALHSILNAAIMISVIVVMTILLVVLYKYRCYKVIHAWLIISSLLLLFFFSFI
YLGEVFKTYNVAVDYITVALLIWNFGVVGMISIHWKGPLRLQQAYLIMISALMALVFIKY
LPEWTAWLILAVISVYDLVAVLCPKGPLRMLVETAQERNETLFPALIYSSTMVWLVNMAE
GDPEAQRRVSKNSKYNAESTERESQDTVAENDDGGFSEEWEAQRDSHLGPHRSTPESRAA
VQELSSSILAGEDPEERGVKLGLGDFIFYSVLVGKASATASGDWNTTIACFVAILIGLCL
TLLLLAIFKKALPALPISITFGLVFYFATDYLVQPFMDQLAFHQFYI'

# from https://rest.uniprot.org/uniprotkb/Q9W6T7.fasta
zPsen1 <- 'MADLVQNAANNVLNDGMDTSRHTSSTAAPPSRNEVELNGQPPTAPPPQVVTDSEEDEDEE
LTLKYGAKHVIMLFIPVTLCMVVVVATIKSVSFYTQKDGQQLIYTPFREDTETVGQRALH
SMLNAIIMISVIVVMTLVLVVLYKYRCYKVIQAWLFFSNLLLLFFFSLIYLGEVFKTYNV
AMDYFTLALIIWNFGVVGMICIHWKGPLRLQQAYLIMISALMALVFIKYLPEWTAWLILA
AISVYDLLAVLCPKGPLRILVETAQERNEAIFPALIYSSTMVWLFNMADSAETRNNSSHP
VPQQENQVVAMAPTAQAEDDGGFTPAWVDHQQHQLGPMQSTEESRRQIQEMPSARPPPPA
DDDEERGVKLGLGDFIFYSMLVGKASATASGDWNTTLACFVAILIGLCLTLLLLAIFKKA
LPALPISITFGLVFYFATDNLVRPFMDQLAVHQFYI'

proteinAligner(human=hPsen1,
               zebrafish=zPsen1,
               cols=c('#ffffff', '#c0c4c4', '#db5072', '#8f66ac', '#766dbf', '#437ce6', '#3c3c3c'),
               proteinname='psen1',
               spaceBetween=0.6,
               width=75,
               height=14,
               exportFolder=here('proteinAlignments'))

proteinAligner(human=hPsen1,
               zebrafish=zPsen1,
               # labelhumanpos=c(257, 385),
               cols=c('#ffffff', '#c0c4c4', '#cb2a20', '#a24b4b', '#8a5f65', '#697a87'),
               proteinname='psen1',
               spaceBetween=0.6,
               width=75,
               height=14,
               exportFolder=here('proteinAlignments'))



# psen2 -------------------------------------------------------------------

# from https://rest.uniprot.org/uniprotkb/P49810.fasta
hPsen2 <- 'MLTFMASDSEEEVCDERTSLMSAESPTPRSCQEGRQGPEDGENTAQWRSQENEEDGEEDP
DRYVCSGVPGRPPGLEEELTLKYGAKHVIMLFVPVTLCMIVVVATIKSVRFYTEKNGQLI
YTPFTEDTPSVGQRLLNSVLNTLIMISVIVVMTIFLVVLYKYRCYKFIHGWLIMSSLMLL
FLFTYIYLGEVLKTYNVAMDYPTLLLTVWNFGAVGMVCIHWKGPLVLQQAYLIMISALMA
LVFIKYLPEWSAWVILGAISVYDLVAVLCPKGPLRMLVETAQERNEPIFPALIYSSAMVW
TVGMAKLDPSSQGALQLPYDPEMEEDSYDSFGEPSYPEVFEPPLTGYPGEELEEEEERGV
KLGLGDFIFYSVLVGKAAATGSGDWNTTLACFVAILIGLCLTLLLLAVFKKALPALPISI
TFGLIFYFSTDNLVRPFMDTLASHQLYI'

# from https://rest.uniprot.org/uniprotkb/Q90ZE4.fasta
zPsen2 <- 'MNTSDSEEDSYNERSALVQSESPTVPSYNQDNAMSLPQDTDSKRSGAVRSRSASGSGDAG
PVDRERADTPDGEEEELTLKYGAKHVIMLFIPVTLCMVVVVATIKSVSFYTEKSGQRLIY
TPFEEDPNSVGQRLLNSVLNTLVMISVIVFMTIILVLLYKYRCYKFIHGWLILSSLMLLF
WFSFMYLGEVFKTYNVAMDYPTLLMIIWNFGVVGMICIHWKGPLRLQQAYLIVISALMAL
IFIKYLPEWSAWVILGAISIYDLIAVLCPKGPLRMLVETAQERNEPIFPALIYSSAMVWM
VGMADSNNPDSAGERRRSGGGVRTQEGVESEHDAPQAGRRQYSAEEDLEEDRGVKLGLGD
FIFYSVLVGKAAATGGDWNTTLACFVAILIGLCLTLLLLAIFKKALPALPISITFGLVFY
FSTDNLVRPFMDSLAAHQYYI'

proteinAligner(human=hPsen2,
               zebrafish=zPsen2,
               cols=c('#ffffff', '#c0c4c4', '#db5072', '#8f66ac', '#766dbf', '#437ce6', '#3c3c3c'),
               # labelhumanpos=c(263, 366),
               # labelhumanpos=c(296, 337), # second disordered domain called from AlphaFold
               proteinname='psen2',
               spaceBetween=0.6,
               width=75,
               height=14,
               exportFolder=here('proteinAlignments'))



# sorl1 -------------------------------------------------------------------

# from https://rest.uniprot.org/uniprotkb/Q92673.fasta
hSorl1 <- 'MATRSSRRESRLPFLFTLVALLPPGALCEVWTQRLHGGSAPLPQDRGFLVVQGDPRELRL
WARGDARGASRADEKPLRRKRSAALQPEPIKVYGQVSLNDSHNQMVVHWAGEKSNVIVAL
ARDSLALARPKSSDVYVSYDYGKSFKKISDKLNFGLGNRSEAVIAQFYHSPADNKRYIFA
DAYAQYLWITFDFCNTLQGFSIPFRAADLLLHSKASNLLLGFDRSHPNKQLWKSDDFGQT
WIMIQEHVKSFSWGIDPYDKPNTIYIERHEPSGYSTVFRSTDFFQSRENQEVILEEVRDF
QLRDKYMFATKVVHLLGSEQQSSVQLWVSFGRKPMRAAQFVTRHPINEYYIADASEDQVF
VCVSHSNNRTNLYISEAEGLKFSLSLENVLYYSPGGAGSDTLVRYFANEPFADFHRVEGL
QGVYIATLINGSMNEENMRSVITFDKGGTWEFLQAPAFTGYGEKINCELSQGCSLHLAQR
LSQLLNLQLRRMPILSKESAPGLIIATGSVGKNLASKTNVYISSSAGARWREALPGPHYY
TWGDHGGIITAIAQGMETNELKYSTNEGETWKTFIFSEKPVFVYGLLTEPGEKSTVFTIF
GSNKENVHSWLILQVNATDALGVPCTENDYKLWSPSDERGNECLLGHKTVFKRRTPHATC
FNGEDFDRPVVVSNCSCTREDYECDFGFKMSEDLSLEVCVPDPEFSGKSYSPPVPCPVGS
TYRRTRGYRKISGDTCSGGDVEARLEGELVPCPLAEENEFILYAVRKSIYRYDLASGATE
QLPLTGLRAAVALDFDYEHNCLYWSDLALDVIQRLCLNGSTGQEVIINSGLETVEALAFE
PLSQLLYWVDAGFKKIEVANPDGDFRLTIVNSSVLDRPRALVLVPQEGVMFWTDWGDLKP
GIYRSNMDGSAAYHLVSEDVKWPNGISVDDQWIYWTDAYLECIERITFSGQQRSVILDNL
PHPYAIAVFKNEIYWDDWSQLSIFRASKYSGSQMEILANQLTGLMDMKIFYKGKNTGSNA
CVPRPCSLLCLPKANNSRSCRCPEDVSSSVLPSGDLMCDCPQGYQLKNNTCVKQENTCLR
NQYRCSNGNCINSIWWCDFDNDCGDMSDERNCPTTICDLDTQFRCQESGTCIPLSYKCDL
EDDCGDNSDESHCEMHQCRSDEYNCSSGMCIRSSWVCDGDNDCRDWSDEANCTAIYHTCE
ASNFQCRNGHCIPQRWACDGDTDCQDGSDEDPVNCEKKCNGFRCPNGTCIPSSKHCDGLR
DCSDGSDEQHCEPLCTHFMDFVCKNRQQCLFHSMVCDGIIQCRDGSDEDAAFAGCSQDPE
FHKVCDEFGFQCQNGVCISLIWKCDGMDDCGDYSDEANCENPTEAPNCSRYFQFRCENGH
CIPNRWKCDRENDCGDWSDEKDCGDSHILPFSTPGPSTCLPNYYRCSSGTCVMDTWVCDG
YRDCADGSDEEACPLLANVTAASTPTQLGRCDRFEFECHQPKTCIPNWKRCDGHQDCQDG
RDEANCPTHSTLTCMSREFQCEDGEACIVLSERCDGFLDCSDESDEKACSDELTVYKVQN
LQWTADFSGDVTLTWMRPKKMPSASCVYNVYYRVVGESIWKTLETHSNKTNTVLKVLKPD
TTYQVKVQVQCLSKAHNTNDFVTLRTPEGLPDAPRNLQLSLPREAEGVIVGHWAPPIHTH
GLIREYIVEYSRSGSKMWASQRAASNFTEIKNLLVNTLYTVRVAAVTSRGIGNWSDSKSI
TTIKGKVIPPPDIHIDSYGENYLSFTLTMESDIKVNGYVVNLFWAFDTHKQERRTLNFRG
SILSHKVGNLTAHTSYEISAWAKTDLGDSPLAFEHVMTRGVRPPAPSLKAKAINQTAVEC
TWTGPRNVVYGIFYATSFLDLYRNPKSLTTSLHNKTVIVSKDEQYLFLVRVVVPYQGPSS
DYVVVKMIPDSRLPPRHLHVVHTGKTSVVIKWESPYDSPDQDLLYAVAVKDLIRKTDRSY
KVKSRNSTVEYTLNKLEPGGKYHIIVQLGNMSKDSSIKITTVSLSAPDALKIITENDHVL
LFWKSLALKEKHFNESRGYEIHMFDSAMNITAYLGNTTDNFFKISNLKMGHNYTFTVQAR
CLFGNQICGEPAILLYDELGSGADASATQAARSTDVAAVVVPILFLILLSLGVGFAILYT
KHRRLQSSFTAFANSHYSSRLGSAIFSSGDDLGEDDEDAPMITGFSDDVPMVIA'

# from https://rest.uniprot.org/uniprotkb/Q90ZE4.fasta
zSorl1 <- 'MASGQTRKMLALSRCAIYLLLLLVPAAISSTLRLHHDQRFVLPQDRGFSLVSAHLEPAES
RVVRLEREVREASAAHQLRVRRNAAGAPVPNVYGMANLNDSHNQMVVHWAGEKSDVIVAL
ARDSVGATDPKTSSVYVSYDYGANFTPVSEKFQLPREQEDKKQVISQFYHSPADNKRYLF
TDTTNSYLWNTFDFCKTVQGFSIPFKPTDLLLHSKRPNLVLGYDSSHPNKQLWKSDDFGE
TWVLIQEHVKFYFWGVEPYDNPTTVFVQRHEPQGDSSILTSTDFFQSEQNRRIILEKVDS
FQLRDKYMFATTTRALLGSHESQSVQLWVSYNRQPMRAAQFNTRHPITEYYIADASEDQV
FVCVNHNNNVTHLYISDTQGLSFSLSLENVLYFSPDGSGSNTLIRYFANEPFADLHRVEG
LRGVFVATLINGSVSEDNMRSVITFDKGGTWELLQPPAADSLGGTIDCQLNSGCSLHLAQ
RWSQLLNIQLRRIPILSKESAPGLIMATGSVGKNMANKPNVYVSSSAGVRWREALAGPHF
YTWGDHGGILMAIAQGGSSKTLKYSTNEGETWKEFQFSKQEVYVYQLLTEPGEKSTIFTI
FGSYADQKHSWLIVQVNASDVLGVPCSEGDYKLWSPSDERGNGCLLGREMVYKRRSPHAT
CFNGEDFDRPISLSNCSCTRQDYECDYGFKLSEDLSLEVCVPDPEFSGNLYAPPVPCPVG
TTYHRSKGYRKVSGDSCTGGDVEARLDGENLPCPVGESNEFILYAVRNSIHRYDLASGTD
QQLPLTGLHEAVALDFDYEKNCLYWADISLDTIQRLCMNGSSGQEVIVKRDLQNVEALSF
DPISRLLYWVDAGAQKIEVSNSDGDLRRTLVNSSVVDQPRALALMPAESLMFWTDWGDRA
AGVYRSWMDGSNISCIVSEGVRWPNGITADESWLYWTEAYGDRIERADFNGGSRTVIMEG
LPHPYAIAVFKNDLYWDDWSRMGIFKAPKSGSPDSELIVGRLTGVMDLKIFYKGKNRGQN
ACADQPCSLLCLPQPGNQRHCVCPDGVPTSVLPSGERQCQCPSGYQLHNNTCVKTEHTCL
PNQHRCANGKCISSIWKCDSDNDCGDMSDEQECPTTSCDPSVQFRCVASGSCIPLAFKCD
HEDDCGDNSDEEHCESHKCGPGEFTCARGACIRDAWRCDGDNDCRDWSDEANCTVGHHTC
ESSSFQCHTGHCIPQRWVCDGDDDCQDGSDEDPTQCGRQKCNGFLCSNGTCLPASAHCNG
VEDCPGGADEQNCGPLCAHYMEFVCRNRAQCLFQSLVCDGTRHCADGSDEDPIYAGCSTS
VEFEKTCDGYNFQCTNGMCVTLEWKCDGMDDCGDYSDEANCASPTEEPGCTSYFRFECKN
GRCVPAWWKCDGENDCGDWSDESQCSGGEALHTPAPGPATCAPNRFRCGSGACIVDTWVC
DGYADCPDSSDEAGCPTVKGSVTSVTTLPPSGRCTKDQFLCVKPPACISDWKRCDGHSHC
LDGSDEANCPTHGPLLCANGTRCADGEACLLNSERCDGFIDCSDRSDEHNCTDEQQVYKV
QNLQWTANFSGAVKLTWTRPKNMPTSSCSFVIYFRPVGVQQWTSIDTNSNKGSAVLTVLM
PDTTYNVKVQTQCLSKQHRTNEYLTLRTPEGLPDPPQSLQLSCDKADDGTVLCSWSPPDK
THGHIREYIVEYSEKDSAEWFSLSSTSTNAEVKNLQPSSLYRFRVAAVTSRGVGNWTEIK
SIIPQKALSPPKVTITSITEDSMSLSISNDYKVKVKLYIVVISWVFDEHVKESWNYTVPE
TLKVSNLTAGTEYEVAVWAHTDDGDSPTALSRQQTKGSRPVQPSLKARALNQTAVDCNWT
GPPAEMYAVFYATSFLDLFRRPHRVNSTSSSLTVIVDSDEQYLFLVRVVSPYMGPPSNYA
VVKMIPDERLPPRNLHKVRVDKTQATLKWQPPYDSPSSPLTYAVHVRDTVRKTESDYKVI
TQNNTVEYTLKGLEPAGRYSITIRLLNMSKEASYTLSTVPLPAPEALKILEEEDHVFLFW
KSLAVKDRTFNESRGYEVYVHDSVTNSTKCLGNTTETFFRINSLLAGHNYTFSVRARCLL
SNQLCGESAVLLYDELGKAAGQNDAASQSGKSEDMAAIVVPVLFLLLVGVCGGLVVLYLR
HRRLQHSFTAFANSHYNSRLGSAIFSSGDELGDDDEDAPMISGFSDDVPMVIA'

proteinAligner(human=hSorl1,
               zebrafish=zSorl1,
               cols=c('#ffffff', '#c0c4c4', '#db5072', '#8f66ac', '#766dbf', '#437ce6', '#3c3c3c'),
               proteinname='sorl1',
               spaceBetween=1,
               width=83,
               height=20,
               exportFolder=here('proteinAlignments'))



# clu ---------------------------------------------------------------------

# from https://rest.uniprot.org/uniprotkb/P10909.fasta
hClu <- 'MMKTLLLFVGLLLTWESGQVLGDQTVSDNELQEMSNQGSKYVNKEIQNAVNGVKQIKTLI
EKTNEERKTLLSNLEEAKKKKEDALNETRESETKLKELPGVCNETMMALWEECKPCLKQT
CMKFYARVCRSGSGLVGRQLEEFLNQSSPFYFWMNGDRIDSLLENDRQQTHMLDVMQDHF
SRASSIIDELFQDRFFTREPQDTYHYLPFSLPHRRPHFFFPKSRIVRSLMPFSPYEPLNF
HAMFQPFLEMIHEAQQAMDIHFHSPAFQHPPTEFIREGDDDRTVCREIRHNSTGCLRMKD
QCDKCREILSVDCSTNNPSQAKLRRELDESLQVAERLTRKYNELLKSYQWKMLNTSSLLE
QLNEQFNWVSRLANLTQGEDQYYLRVTTVASHTSDSDVPSGVTEVVVKLFDSDPITVTVP
VEVSRKNPKFMETVAEKALQEYRKKHREE'

# zebrafish, options
# https://rest.uniprot.org/uniprotkb/Q6PBL3.fasta

# Ensembl for transcript clu_201 links to https://rest.uniprot.org/uniparc/UPI0000437847.fasta
# which is marked as obsolete and 99.5% identical to Q6PBL3.fasta
# ZFIN links to https://rest.uniprot.org/uniparc/UPI0005A569C6.fasta
# which is marked as obsolete and also 99.5% identical to Q6PBL3.fasta
zClu <- 'MKVLWSLLGLFLLYLSTECLLPPSKEELNQMSQVGEKYLDRQIENAISGVKEMKTVMERS
EEEHKRMLSEMEKTQKEKENALKTAQEMKEKLSEEQSVCNETMEALWEECKPCLRKTCVK
FYSRTCRSGSGLVGRQLEEILNRTSPISIFINGQSIETLLSEDQQQTRHFQDLEESYTEV
SDGVENMFTDSMKVFDHMQMFHHPGFFPSRFQFPSMFGGHEGSTHAGRIYRSPMHDSLFH
SLQSLFRPMERSMSMFGKNEERNFTSEGWKLNEKVTTDDKMTCKEIRRNSFGCVKLKDEC
EKCQQIQHIDCSGKRPLEGPLKEELERALGKAEEFTQEFNNLLNIFQEQMFNTSSLLDLF
NKQFGWVSSLANHTQNEDGFFQIQAVMSKGSDNAENPADTRVSVKLFDGPDMIYTVPGDI
PWSDPKFSEVVAQEALDRYKQNAVITKL'

proteinAligner(human=hClu,
               zebrafish=zClu,
               cols=c('#ffffff', '#c0c4c4', '#db5072', '#8f66ac', '#766dbf', '#437ce6', '#3c3c3c'),
               proteinname='clu',
               spaceBetween=0.6,
               width=75,
               height=14,
               exportFolder=here('proteinAlignments'))


# cd2ap -------------------------------------------------------------------


# from https://rest.uniprot.org/uniprotkb/Q9Y5K6.fasta
hCd2ap <- 'MVDYIVEYDYDAVHDDELTIRVGEIIRNVKKLQEEGWLEGELNGRRGMFPDNFVKEIKRE
TEFKDDSLPIKRERHGNVASLVQRISTYGLPAGGIQPHPQTKNIKKKTKKRQCKVLFEYI
PQNEDELELKVGDIIDINEEVEEGWWSGTLNNKLGLFPSNFVKELEVTDDGETHEAQDDS
ETVLAGPTSPIPSLGNVSETASGSVTQPKKIRGIGFGDIFKEGSVKLRTRTSSSETEEKK
PEKPLILQSLGPKTQSVEITKTDTEGKIKAKEYCRTLFAYEGTNEDELTFKEGEIIHLIS
KETGEAGWWRGELNGKEGVFPDNFAVQINELDKDFPKPKKPPPPAKAPAPKPELIAAEKK
YFSLKPEEKDEKSTLEQKPSKPAAPQVPPKKPTPPTKASNLLRSSGTVYPKRPEKPVPPP
PPIAKINGEVSSISSKFETEPVSKLKLDSEQLPLRPKSVDFDSLTVRTSKETDVVNFDDI
ASSENLLHLTANRPKMPGRRLPGRFNGGHSPTHSPEKILKLPKEEDSANLKPSELKKDTC
YSPKPSVYLSTPSSASKANTTAFLTPLEIKAKVETDDVKKNSLDELRAQIIELLCIVEAL
KKDHGKELEKLRKDLEEEKTMRSNLEMEIEKLKKAVLSS'

# zebrafish, options:
# top result in Uniprot is https://rest.uniprot.org/uniprotkb/F1R1N9.fasta
# ZFIN links to this one
# Ensembl too

zCd2ap <- 'MVEVVVEYEYEALHEDELTLRLGDIIKNVRRIEEEGWMEGDLNGKRGLFPDNFVKEVRKD
EPKSKEESKEPKEAKEVKEESTIQRRASGNVASLVQRISTYGIPAGGIGLQPHSQPRASK
KKLKKRQCKVLFEYVPQNEDELELKVGEIIEITEEVEEGWWSGSMNGKSGLFPSNFVKEI
DSTEDAENSDVTEEQDTRDGTSSPTSPHPGNGVMAQPKKIKGIGFGDIFREGSVKLRTSL
KGPSENMEKTEKPIPPLPSATKPTPLSTPEHPKGEKEAESKAKVKEYCKATFHYEATNQD
ELDLKEGEVILILSKDTGEPGWWRGEVNGKQGVFPDNFVSLLPESDKETLTSKGSIKVLS
KQEPEERPKKPPPPSKSTVLKPETPSVDKKQPQPRPEDKVVKPLPEKPAKPAGPIVPPKK
PVPPSKSLLRPSYHTKRPDLPLTPSPAAKQVQNGDVPLSRRKSECEPVPIKPKTVVDIGE
KSTETVNLMSFDDVSSSSEKLSHPTAQRPKMPGKRPPAHRGHSPSKDVGEKAEKTEKIDE
VETAPSPAPAPAPAPSTQNSIKMPISSPLPSTTPKTISATLITPEPKPKPDKEQEKTSEL
EELKDQIKDLVLSVELLKTQQSRELGELRKELDDERLKRVALQMEIDKLKKICVQST'

proteinAligner(human=hCd2ap,
               zebrafish=zCd2ap,
               cols=c('#ffffff', '#c0c4c4', '#db5072', '#8f66ac', '#766dbf', '#437ce6', '#3c3c3c'),
               proteinname='cd2ap',
               spaceBetween=0.6,
               width=75,
               height=14,
               exportFolder=here('proteinAlignments'))




# APOE vs Apoea -----------------------------------------------------------

# from https://rest.uniprot.org/uniprotkb/P02649.fasta
hApoe <- 'MKVLWAALLVTFLAGCQAKVEQAVETEPEPELRQQTEWQSGQRWELALGRFWDYLRWVQT
LSEQVQEELLSSQVTQELRALMDETMKELKAYKSELEEQLTPVAEETRARLSKELQAAQA
RLGADMEDVCGRLVQYRGEVQAMLGQSTEELRVRLASHLRKLRKRLLRDADDLQKRLAVY
QAGAREGAERGLSAIRERLGPLVEQGRVRAATVGSLAGQPLQERAQAWGERLRARMEEMG
SRTRDRLDEVKEQVAEVRAKLEEQAQQIRLQAEAFQARLKSWFEPLVEDMQRQWAGLVEK
VQAAVGTSAAPVPSDNH'

# zebrafish Apoea, options:
# only result in Uniprot is https://rest.uniprot.org/uniprotkb/Q503V2.fasta
# ZFIN links to this one
# Ensembl too

zApoea <- 'MKFVAVIVALAVISGCQGRFLFQDEPRSRWEEAVDQFWNHVSELTTRAEEMRDNIKATQL
GRELDTLISDSMMELQMYRDDLHSKLAPYAQERAQKFNEDLQLLVTKLRTHMEEAKDRVT
EYTEELRTMVEQNSDELKNKANSYAKKLRKRFNKDIQEINKKMSTYLEEVQSRASQSVED
VKDRLEPYFTSMHERAQQKLVNLREALRSQAEEIKERLDSRMQELRDQVEKTKENVHNTL
QQKAEDVQKWFEPYVSHIQKQMEPVWESL'

proteinAligner(human=hApoe,
               zebrafish=zApoea,
               cols=c('#ffffff', '#c0c4c4', '#db5072', '#8f66ac', '#766dbf', '#437ce6', '#3c3c3c'),
               proteinname='apoea',
               spaceBetween=0.6,
               width=75,
               height=14,
               exportFolder=here('proteinAlignments'))


# APOE vs Apoeb -----------------------------------------------------------

# from https://rest.uniprot.org/uniprotkb/P02649.fasta
hApoe <- 'MKVLWAALLVTFLAGCQAKVEQAVETEPEPELRQQTEWQSGQRWELALGRFWDYLRWVQT
LSEQVQEELLSSQVTQELRALMDETMKELKAYKSELEEQLTPVAEETRARLSKELQAAQA
RLGADMEDVCGRLVQYRGEVQAMLGQSTEELRVRLASHLRKLRKRLLRDADDLQKRLAVY
QAGAREGAERGLSAIRERLGPLVEQGRVRAATVGSLAGQPLQERAQAWGERLRARMEEMG
SRTRDRLDEVKEQVAEVRAKLEEQAQQIRLQAEAFQARLKSWFEPLVEDMQRQWAGLVEK
VQAAVGTSAAPVPSDNH'

# zebrafish Apoea, options:
# only result in Uniprot is https://rest.uniprot.org/uniprotkb/O42364.fasta
# ZFIN links to obsolete https://rest.uniprot.org/uniparc/UPI00015DAC26.fasta
# Ensembl links to O42364.fasta, will use this one

zApoeb <- 'MRSLVVFFALAVLTGCQARSLFQADAPQPRWEEMVDRFWQYVSELNTQTDGMVQNIKGSQ
LSRELDTLITDTMAELSSYSENLQTQMTPYASDAAGQLSKDLQLLAGKLQTDMTDAKERS
TQYLQELKTMMEQNADDVKNRVGTYTRKLKKRLNKDTEEIRNTVATYMSEMQSRASQNAD
AVKDRFQPYMSQAQDGATQKLGAISELMKAQAQEVSEQLEVQAGALKEKLEETAENLRTS
LEGRVDELTSLLAPYSQKIREQLQEVMDKIKEATAALPTQA'

proteinAligner(human=hApoe,
               zebrafish=zApoeb,
               cols=c('#ffffff', '#c0c4c4', '#db5072', '#8f66ac', '#766dbf', '#437ce6', '#3c3c3c'),
               proteinname='apoeb',
               spaceBetween=0.6,
               width=75,
               height=14,
               exportFolder=here('proteinAlignments'))



# APP vs Appa -------------------------------------------------------------

# from https://rest.uniprot.org/uniprotkb/P05067.fasta
hApp <- 'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTK
TCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVG
EFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFR
GVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEE
EADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPC
RAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARD
PVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQA
KNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITAL
QAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYER
MNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTET
KTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTN
IKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITL
VMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN'

# zebrafish Appa, options:
# only result in Uniprot is https://rest.uniprot.org/uniprotkb/Q6NUZ1.fasta
# ZFIN links to obsolete https://rest.uniprot.org/uniparc/UPI00062E35D5.fasta
# Ensembl appa-202 links to obsolete https://rest.uniprot.org/uniparc/UPI00062E35D5.fasta, same as ZFIN
# both are 96.48% identity and give similar identity to human (67 for Uniprot vs 65 for obsolete)
# will use Uniprot, not obsolete

zAppa <- 'MRSRELFILLMAVASTLAVEVPSDSGTGLLAEPQIAMFCGKLNMHINIQSGKWEPDPSGS
KSCIGNKEGILQYCQEVYPELQITNVVEANQPVSIWDWCKKSRKQCRSHMHIVVPYRCLV
GEFVSDALLVPDKCKFLHQERMDMCESHLHWHTVAKESCGDRSMNLHDYGMLLPCGIDRF
RGVEFVCCPADAGKESESAAVEEDDSDVWWGGAEADYTENSMTRDAAAEPAVLEDDEDAD
EEEDEDQDGDGDRDEKIEEEEEEEERTQSTSAALTSTTTTTTESVEEVVREVCFASAETG
PCRAMLSRWYYVREERRCAPFIYGGCGGNRNNFESEEYCLSVCSGVLPTPSSSPPDAVDR
YLETPADENEHAHFLQAKESLETKHRERMSQVMREWEEAERQAKSLPRNDKKAVIQHFQE
KVEALEQESASERQQLVETHMARVEALLNDRRRLALESYLSALQADPPRPRHVFSLLKKY
VRAEQKDRQHTLKHFEHVRMVDPKKAAQIRPQVLTHLRVIEERMNQSLGLLYKVPGVADD
IQDQVELLQREQQEMSAQLANLQSDARVSYGNDALMPDSTAGLELLPAEDTQGFGFIHPE
SFNQPNTHNQVEPVDARPVPDLDLATRPVSGLKPDDIPELRMEAEERHSEVYHQKLVFFA
EDVSSNKGAIIGLMVGGVVIATIIVITLVMLRKKQYTSIHHGIIEVDAAVTPEERHLSKM
QQNGYENPTYKFFEQMHN'

proteinAligner(human=hApp,
               zebrafish=zAppa,
               cols=c('#ffffff', '#c0c4c4', '#db5072', '#8f66ac', '#766dbf', '#437ce6', '#3c3c3c'),
               proteinname='appa',
               spaceBetween=0.6,
               width=75,
               height=14,
               exportFolder=here('proteinAlignments'))



# APP vs Appb -------------------------------------------------------------

# from https://rest.uniprot.org/uniprotkb/P05067.fasta
hApp <- 'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTK
TCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVG
EFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFR
GVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEE
EADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPC
RAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARD
PVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQA
KNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITAL
QAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYER
MNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTET
KTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTN
IKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITL
VMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN'

# zebrafish Appb, options:
# top result in Uniprot is https://rest.uniprot.org/uniprotkb/B0V0E5.fasta
# ZFIN links to same
# Ensembl appb-203 links to same

zAppb <- 'MGMDRTVFLLLMLTTLSLAIEVPSDDSVGLLAEPQVAMFCGKLNMHINVQSGKWEPDPTG
TKSCISTKEGILQYCQEVYPDLQITNVVEANQPVSIQNWCKMGRRQCRSHTHIVVPYRCL
VGEFVSDALLVPDKCKFLHQERMDMCESHLHWHTVAKESCGDRSMNLHDYGMLLPCGIDR
FRGVEFVCCPMEEQKDLDSEEQEEANSDVWWGGAETEYTDASVLKEQVTAKPDPAVTEDD
EDLNNEEDQVWDNDEDGDGEDDEDEEDDDEDIIDEQDTSEQTSNIAMTTTTTTTTESIEE
VVRAVCWAPARSGPCHAKLPRWYFVAEKGRCASFTFGGCGGNRNNFESEEYCMAVCSSSV
LPTMAPSPADAVDRYLEAPGDINEHMRFQKAKESLEAKHREKMSEVMREWEEAERQAKNL
PRADKKTIIQRFQEKVESLEKEAAGERQQLVETHMARVEALLNDRRRQALESYLSSLQSD
QPRPRQVLNLLKKYIRAEQKDRQHTLKHFEHVREVDPKKASQIRPFVMTHLRVIEERMNQ
SLGYLYKVPQVANDIQDQVAVLVQRDQAEVTQQLSSLQSKMRVSYGNDALMPDLPDSTTP
LDNLPPEQDGLGFIHPESFNQANTDNHVEPVDARPIPERGLPTRPEIPKVRLDIEERHNA
GYDVRDKRLMFLAEDMGSNKGAIIGLMVGGVVIATVIVITLVMLRKKQYTSIHHGVIEVD
AAVTPEERHLAKMQQNGYENPTYKFFEQMQN'

proteinAligner(human=hApp,
               zebrafish=zAppb,
               cols=c('#ffffff', '#c0c4c4', '#db5072', '#8f66ac', '#766dbf', '#437ce6', '#3c3c3c'),
               proteinname='appb',
               spaceBetween=0.6,
               width=75,
               height=14,
               exportFolder=here('proteinAlignments'))



# human amyloid beta vs from Appa -----------------------------------------

# ! need to edit margin otherwise gets cropped
# in proteinAligner, change to
# plot.margin=margin(t=-2, r=0, b=-3, l=0)
# and then put back as
# plot.margin=margin(t=-2, r=-8, b=-3, l=-14)
# otherwise will need to fix all figures done already

# sequences are from figure I made long time ago app_cleavage.pdf
# should check again carefully

hAB <- 'DAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIA'
zABa <- 'EAEERHSEVYHQKLVFFAEDVSSNKGAIIGLMVGGVVIA'
zABb <- 'DIEERHNAGYDVRDKRLMFLAEDMGSNKGAIIGLMVGGVVIA'

proteinAligner(human=hAB,
               zebrafish=zABa,
               cols=c('#ffffff', '#c0c4c4', '#cb2a20', '#a24b4b', '#8a5f65', '#697a87'),
               proteinname='ABa',
               spaceBetween=1.7,
               width=35,
               height=5,
               exportFolder=here('proteinAlignments'))

proteinAligner(human=hAB,
               zebrafish=zABb,
               cols=c('#ffffff', '#c0c4c4', '#cb2a20', '#a24b4b', '#8a5f65', '#697a87'),
               proteinname='ABb',
               spaceBetween=1.7,
               width=35,
               height=5,
               exportFolder=here('proteinAlignments'))
